export default {

	INITIALIZE: 'INITIALIZE',
	MAPS_ADD: 'MAPS_ADD',
	MAPS_REMOVE: 'MAPS_REMOVE',
	MAPS_UPDATE: 'MAPS_UPDATE',
	MAPS_UPDATE_DEFAULTS: 'MAPS_UPDATE_DEFAULTS',
	MAPS_SET_ACTIVE: 'MAPS_SET_ACTIVE',
	MAPS_SET_INDEPENDENT_OF_PERIOD: 'MAPS_SET_INDEPENDENT_OF_PERIOD'
};
