export default {
	SCENARIOS_DEFAULT_SITUATION_NAME: 'Default state',
	SCENARIOS_PROCESSING_FILE_LOADER_TEXT: 'Processing file...',
	SCENARIOS_PROCESSING_FILE_ERROR: 'Error',
	SCENARIOS_PROCESSING_FILE_ERROR_MESSAGE: 'Error during file processing!',
	SCENARIOS_PROCESSING_FILE_SUCCESS: 'Success',
	SCENARIOS_PROCESSING_FILE_SUCCESS_MESSAGE: 'File was processed successfully!'
};
