var langEn = {
    abstract: "Abstract",
    activateDeactivate: "Activate/deactivate",
    add: "Add",
    addChart: "Add chart",
    addLayer: "Add layer",
    advanced: "Advanced",
    aggregate: "Aggregate",
    all: "All",
    allAttributesHaveToBeNormalized: 'All attributes have to be normalized to "First selected"',
    allPlaces: "All places",
    analysis: "Analysis",
    analyticalUnits: "Analytical units",
    anonymous: "Anonymous ",
    apply: "Apply",
    areaOutlines: "Area outlines",
    area: "Area",
    areas: "Areas",
    areasAmount: "Areas {0} - {1} of {2}",
    areaUnits: "Area units",
    attribute: "Attribute",
    attributeSet: "Attribute set",
    attributeUnitDisplayed: "Attribute unit - displayed",
    attributeUnitOriginal: "Attribute unit - original",
    availableLayers: "Available layers",
    average: "Average",

    back: "Back",
    backgroundLayers: "Background layers",
    badCredentials: "Bad credentials",
    bulkEditConfiguration: "You can bulk edit configuration only for attributes with the same source units, same normalization type, change units, custom factor and for attribute and attribute set normalization also the same attribute and/or attribute set.",

    cancel: "Cancel",
    cat: "Cat.",
    categorize: "Categorize",
    changeSettings: "Change Settings",
    choroplethParams: "Choropleth params",
    classification: "Classification",
    classType: "Class. type",
    clickToDefineLine: "Click to define line shape, double-click to complete.",
    clickToDefinePolygon: "Click to define polygon shape, double-click to complete.",
    closeLegend: "Close legend",
    collapseAll: "Collapse all",
    collapseLastLevel: "Collapse last level",
    column: "Column",
    compare: "Compare",
    completeMetadata: "Complete Metadata",
    config: "Config",
    configureFilters: "Configure filters",
    configureThematicMaps: "Configure thematic maps",
    contact: "Contact",
    contextHelp: "Context help",
    continue: "Continue",
    continuous: "Continuous",
    createBlank: "Create blank",
    createCopy: "Create copy",
    create: "created",
    customFactor: "Custom factor",
    customFactorTooltip: "<p>The factor by which the default units of the attribute should be multiplied to get the units which will be displayed in this chart.</p>",
    customViews: "Custom views",
    customWms: "Custom WMS",

    dataset: "Dataset: ",
    dataViewUrl: "Data view URL",
    delete: "Delete",
    deleted: " deleted",
    detach: "Detach",
    displayedUnits: "Displayed units",
    double: "Double",
    down: "Down",
    duplicateAttributesNotAllowed: "Duplicate attributes not allowed",

    error: "Error",
    equal: "Equal",
    expandLastLevel: "Expand last level",
    explore: "Explore",
    exportCsv: "Export CSV",
    exportPng: "Export PNG",
    exportZip: "Export ZIP",
    extentOutline: "Extent outline",

    featureInfo: "Feature info",
    filter: "Filter ",
    filtersConfiguration: "Filters configuration",
    focus: "Focus: ",
    forMoreDetailsSee: "For more details see ",

    help: "Help",
    hide: "Hide",
    hover: "Hover",

    incorrectLogin: "Incorrect username or password. Please try again.",
    interpolate: "Interpolate",

    justSelect: "Just Select",

    keywords: "Keywords",

    layer: "Layer",
    layers: "Layers",
    layersAvailable: "Layers available",
    layersSelected: "Layers selected",
    legend: "Legend",
    length: "Length",
    line: "line",
    liveData: "Live data",
    loggedInAs: "Logged in as ",
    login: "Login",
    logIn: "Log in",
    logout: "Logout",
    logOut: "Log out",

    manageVisualizations: "Manage visualizations",
    measureLine: "Measure line",
    measurePolygon: "Measure polygon",
    metadata: "Metadata",
    modifyDisplayedUnits: "Modify Displayed Units",
    modifyDisplayedUnitsText: "<p>Modify units to be displayed in chart only in case you want to display the attribute in units other than those which are set as default for the attribute. e.g. default units are m2 and you want to display the values in km2. <br>Then the values will be multiplied by the Custom Factor (0,000001 in this case).</p>",
    multipleMaps: "Multiple maps",

    name: "Name",
    noAreas: "No areas",
    none: "None",
    normal: "Normal",
    normalization: "Normalization",
    normalizationAttribute: "Normalization Attribute",
    normalizationAttributeAreaUnits: "Normalization attribute area units",
    normalizationAttrSet: "Normalization Attr set",
    normalizationBase: "Normalization base",
    normalizationType: "Normalization type",
    noSuchDataview: "No such dataview",
    notLoggedIn: "Not logged in",
    numCategories: "Num categories",

    ok: "OK",
    onlySelected: "Only selected",
    opacity: "Opacity",
    open: "Open",
    openLegend: "Open legend",
    other: "Other",

    password: "Password",
    percent: "Percent",
    pie: "Pie",
    polygon: "polygon",
    pleaseSelectAreas: "Please select areas...",
    producer: "Producer",
    pumaWebtoolHelp: "PUMA WebTool help",

    quantiles: "Quantiles",

    record: "Record ",
    remove: "Remove",
    reload: "Reload",
    reset: "Reset",

    save: "Save",
    saveAs: "Save as",
    saveAsImage: "Save as image",
    saveDataView: "Save data view",
    saveView: "Save view",
    saveVisualization: "Save visualization",
    scatter: "Scatter",
    searchForMetadataStarted: "Search for metadata has started. Please wait.",
    select: "Select",
    selectAttributesToAdd: "Select attributes to add",
    selectedAreas: "Selected areas",
    selectedAreasFilled: "Selected areas filled",
    selectedLayers: "Selected layers",
    selectInMap: "Select in map",
    selections: "Selections",
    selectPlace: "Select place...",
    selectTheme: "Select theme...",
    selectScope: "Select scope...",
    setting: "Setting",
    shareDataView: "Share data view",
    shareOnPortal: "Share on portal",
    signUp: "Sign up",
    snapshot: "Snapshot",
    snapshotCreationStarted: "Snapshot creation started",
    snapshotDone: "Snapshot done",
    snapshots: "Snapshots",
    stacking: "Stacking",
    started: "started",
    startCreating: "start creating",
    startUpdating: "start updating",
    switchZooming: "Switch zooming",

    table: "Table",
    temporalExtent: "Temporal extent",
    theme: "Theme: ",
    thematicMaps: "Thematic maps",
    thematicMapsConfiguration: "Thematic maps configuration",
    timedOut: "Timed out, process can still be running on server",
    title: "Title",
    treeAll: "Tree all",
    treeLowestLevel: "Tree lowest level",
    type: "Type",

    undefined: "Undefined",
    undefinedError: "Undefined error",
    units: "Units",
    unselectActiveSelection: "Unselect active selection",
    unselectAll: "Unselect all",
    up: "Up",
    updated: "updated",
    URL: "URL",
    user: "User",

    value: "Value",
    visu: "Visualization",
    visualization: "Visualization: ",
    visualizations: "Visualizations",

    warning: "Warning",
    wasReset: " was reset",

    year: "Year: ",

    zoomSelected: "Zoom selected"
};

var langCz = {
    selectAttributesToAdd: "Vyberte atributy k pridani",
    add: "Pridat",
    back: "Zpet"
};

var polyglot = new Polyglot();

if(!Config.language || Config.language == "en") {
    polyglot.extend(langEn);
} else if(Config.language == "cz") {
    polyglot.extend(langCz);
}

window.polyglot = polyglot;