var langEn = {

    abstract: "Abstract",
    activateDeactivate: "Activate/deactivate",
    activateDrawing: "Activate drawing",
    add: "Add",
    addCategory: "Add category",
    addCategorySet: "Add category set",
    addChart: "Add chart",
    adding: "Adding...",
    addingWmsLayerFailed: "Adding WMS layer failed.\n<br>",
    addLayer: "Add layer",
    advanced: "Advanced",
    aggregate: "Aggregate",
    all: "All",
    allAttributes: "All attributes",
    allAttributesHaveToBeNormalized: 'All attributes have to be normalized to "First selected"',
    allOptions: "All options",
    allPlaces: "All places",
    analysis: "Analysis",
    analyticalUnits: "Analytical units",
    analyticalUnitsLayers: "Analytical Units Layers",
    anonymous: "Anonymous ",
    apply: "Apply",
    area: "Area",
    areaOutlines: "Area outlines",
    areas: "Areas",
    areasAmount: "Areas {0} - {1} of {2}",
    areaUnits: "Area units",
    attribute: "Attribute",
    attributesAreMissingNoLinked: "Attributes are missing! Possible reason: There are no linked attribute sets to analytical units for this place.",
    attributesAreMissingPermissions: "Attributes are missing! Possible reason: Current user does not have appropriate permissions for current configuration.",
    attributesAreMissingBrokenLinks: "Attributes are missing! Possible reason: Broken links in visualizations (e.g. non-existing attributes or attribute sets). Try to create visualizations again.",
    attributesAreMissingChoropleths: "Attributes are missing! Possible reason: Choropleths includes non-existing attributes or attribute sets. Try to create choropleths again.",
    attributeSet: "Attribute set",
    attributeUnitDisplayed: "Attribute unit - displayed",
    attributeUnitOriginal: "Attribute unit - original",
    availableLayers: "Available layers",
    average: "Average",

    back: "Back",
    backgroundLayers: "Background layers",
    badCredentials: "Bad credentials",
    bingAerial: "Bing Aerial",
    blueMarble: "Blue Marble",
    bulkEditConfiguration: "You can bulk edit configuration only for attributes with the same source units, same normalization type, change units, custom factor and for attribute and attribute set normalization also the same attribute and/or attribute set.",

    cancel: "Cancel",
    cartoDbBasemap: "Carto DB basemap",
    cat: "Cat.",
    category: "Category",
    categoryBounded: "(Category)",
    categorize: "Categorize",
    changeSettings: "Change Settings",
    choroplethParams: "Choropleth params",
    classification: "Classification",
    classType: "Class. type",
    clearSelection: "Clear selection",
    clickToActivateDeactivateFeatureInfo: "1. Click to activate/deactivate feature info &#13;2. Click on feature in map to get info",
    clickToDefineLine: "Click to define line shape, double-click to complete.",
    clickToDefinePolygon: "Click to define polygon shape, double-click to complete.",
    closeLegend: "Close legend",
    collapseAll: "Collapse all",
    collapseLastLevel: "Collapse last level",
    column: "Column",
    community: "Community",
    compare: "Compare",
    comparePeriods: "Compare periods",
    completeMetadata: "Complete Metadata",
    connectToWms: "Connect to WMS…",
    config: "Config",
    configureFilters: "Configure filters",
    configureThematicMaps: "Configure thematic maps",
    confirm: "Confirm",
    contact: "Contact",
    contextHelp: "Context help",
    continue: "Continue",
    continuous: "Continuous",
    createBlank: "Create blank",
    createCopy: "Create copy",
    create: "created",
    customFactor: "Custom factor",
    customFactorTooltip: "<p>The factor by which the default units of the attribute should be multiplied to get the units which will be displayed in this chart.</p>",
    customViews: "Custom views",
    customWms: "Custom WMS",
    customWmsLayers: "Custom WMS Layers",

    dataset: "Dataset: ",
    datasetIsNotDefined: "Dataset is not defined!",
    dataViewUrl: "Data view URL",
    delete: "Delete",
    deleted: " deleted",
    deleteWholeSet: " Delete whole set ",
    detach: "Detach",
    displayedUnits: "Displayed units",
    double: "Double",
    down: "Down",
    doYouReallyWantToDeleteLine: "Do you really want to delete line ",
    drawCustomAnalyticalUnits: "Draw custom Analytical units",
    drawCustomAnalyticalUnitsIsDisabled: "Drawing of custom analytical units is disabled for All places option. To enable drawing, please select place (pilot).",
    drawGreenConnectivityLine: "Draw Green Connectivity Line",
    drawingOfCustomLinesIsDisabled: "Drawing of custom lines is disabled for All places option. To enable drawing, please select place(pilot).",
    duplicateAttributesNotAllowed: "Duplicate attributes not allowed",

    error: "Error",
    equal: "Equal",
    expandLastLevel: "Expand last level",
    explore: "Explore",
    exportCsv: "Export CSV",
    exportLayerToGeoJson: "Export layer to GeoJSON",
    exportLayerToShp: "Export layer to SHP",
    exportPng: "Export PNG",
    exportToCsv: "Export to CSV",
    exportToGeoJson: "Export to GeoJSON",
    exportToShp: "Export to SHP",
    exportToXls: "Export to XLS",
    exportZip: "Export ZIP",
    extentOutline: "Extent outline",

    failedToSendRequest: "Failed to send request!",
    featureInfo: "Feature info",
    featureNameGid: "Feature name (GID)",
    file: "File",
    fillTheName: "Fill the name!",
    filter: "Filter ",
    filtersConfiguration: "Filters configuration",
    focus: "Focus: ",
    forMoreDetailsSee: "For more details see ",
    functionalUrbanArea: "Functional Urban Areas",

    group: "Group",

    help: "Help",
    hide: "Hide",
    hover: "Hover",

    importFailed: "Import failed",
    importing: "Importing…",
    incorrectLogin: "Incorrect username or password. Please try again.",
    info: "Info",
    infoLayers: "Info Layers",
    interpolate: "Interpolate",
    itWasntPossibleToLoadGroupsUsers: "It wasnt possible to load available users and groups. Please try later. Error: ",

    justSelect: "Just Select",

    keywords: "Keywords",

    layer: "Layer",
    layerImportedSuccessfully: "Layer imported succesfully.",
    layerName: "Layer name",
    layerNameIsMissing: "Layer name is missing",
    layers: "Layers",
    layersAvailable: "Layers available",
    layersSelected: "Layers selected",
    layerSuccessfullyAdded: "Layer successfully added to Custom WMS section.",
    legend: "Legend",
    length: "Length",
    line: "line",
    liveData: "Live data",
    load: "Load",
    loadFromFile: "Load from file…",
    loadWithoutStatistics: "Load Without Statistics",
    loggedInAs: "Logged in as ",
    login: "Login",
    logIn: "Log in",
    logout: "Logout",
    logOut: "Log out",

    manageVisualizations: "Manage visualizations",
    maximise: "Maximise",
    map3d: "3D map",
    mapTools: "Map tools",
    measureLine: "Measure line",
    measurePolygon: "Measure polygon",
    metadata: "Metadata",
    minimise: "Minimise",
    modifyDisplayedUnits: "Modify Displayed Units",
    modifyDisplayedUnitsText: "<p>Modify units to be displayed in chart only in case you want to display the attribute in units other than those which are set as default for the attribute. e.g. default units are m2 and you want to display the values in km2. <br>Then the values will be multiplied by the Custom Factor (0,000001 in this case).</p>",
    multipleMaps: "Multiple maps",
    multiOptions: "Multioptions:",

    name: "Name",
    noAreas: "No areas",
    noAreaSelected: "No area selected",
    none: "None",
    normal: "Normal",
    normalization: "Normalization",
    normalizationAttribute: "Normalization Attribute",
    normalizationAttributeAreaUnits: "Normalization attribute area units",
    normalizationAttrSet: "Normalization Attr set",
    normalizationBase: "Normalization base",
    normalizationType: "Normalization type",
    noSuchDataview: "No such dataview",
    notLoggedIn: "Not logged in",
    numCategories: "Num categories",

    ok: "OK",
    onlySelected: "Only selected",
    opacity: "Opacity",
    open: "Open",
    openLegend: "Open legend",
    openStreetMap: "OpenStreetMap",
    openStreetMaps: "Open Street Maps",
    osm: "OSM",
    osmDataInformation: "<h1>OSM Data information</h1><p>Select the area for which you want to load the 3D buildings. Area is selected by double clicking on the top left corner and bottom right corner.</p>",
    other: "Other",

    password: "Password",
    percent: "Percent",
    period: "Period",
    periods: "Periods",
    pie: "Pie",
    polygon: "polygon",
    pleaseSelectAreas: "Please select areas...",
    producer: "Producer",
    pumaWebtoolHelp: "PUMA WebTool help",

    quantiles: "Quantiles",

    range: "(Range)",
    record: "Record ",
    remove: "Remove",
    reload: "Reload",
    requestHasBeenSent: "Request has been sent...",
    reset: "Reset",

    save: "Save",
    saved: "Saved!",
    saveAs: "Save as",
    saveAsImage: "Save as image",
    saveDataView: "Save data view",
    savedConfigurations: "Saved configurations",
    saveSetName: "Save set name",
    saveView: "Save view",
    saveVisualization: "Save visualization",
    scatter: "Scatter",
    searchForMetadataStarted: "Search for metadata has started. Please wait.",
    select: "Select",
    selectAttributesToAdd: "Select attributes to add",
    selectCity: "",
    selectedAreas: "Selected areas",
    selectedAreasFilled: "Selected areas filled",
    selectedLayers: "Selected layers",
    selectEnd: "Select end",
    selectInMap: "Select in map",
    selections: "Selections",
    selectPeriod: "Select period",
    selectPeriodsToCompare: "Select periods to compare",
    selectPlace: "Select place...",
    selectScope: "Select scope...",
    selectStart: "Select start",
    selectTheme: "Select theme...",
    send: "Send",
    set: "Set",
    setting: "Setting",
    settings: "Settings",
    share: "Share",
    shareDataView: "Share data view",
    shareOnPortal: "Share on portal",
    showCustomAnalyticalUnitsLayer: "Show Custom Analytical units Layer",
    showInChart: "Show in chart",
    signUp: "Sign up",
    snapshot: "Snapshot",
    snapshotCreationStarted: "Snapshot creation started",
    snapshotDone: "Snapshot done",
    snapshots: "Snapshots",
    stacking: "Stacking",
    started: "started",
    startCreating: "start creating",
    startUpdating: "start updating",
    switchZooming: "Switch zooming",

    table: "Table",
    temporalExtent: "Temporal extent",
    theme: "Theme: ",
    thematicLayers: "Thematic Layers",
    thematicMaps: "Thematic maps",
    thematicMapsConfiguration: "Thematic maps configuration",
    theStateWasCorrectlyShared: "The state was correctly shared. The user has access to current state via URL: ",
    thereWasAnIssueWithSharing: "There was an issue with storing current state of the application. Error: ",
    timedOut: "Timed out, process can still be running on server",
    title: "Title",
    treeAll: "Tree all",
    treeLowestLevel: "Tree lowest level",
    type: "Type",

    undefined: "Undefined",
    undefinedError: "Undefined error",
    units: "Units",
    unselectActiveSelection: "Unselect active selection",
    unselectAll: "Unselect all",
    up: "Up",
    updated: "updated",
    urbanDynamicTool: "UrbanDynamic tool",
    URL: "URL",
    user: "User",

    value: "Value",
    visu: "Visualization",
    visualization: "Visualization: ",
    visualizations: "Visualizations",

    warning: "Warning",
    wasReset: " was reset",
    wmsAddress: "WMS address",
    wmsAddressIsMissing: "WMS address is missing or incorrect",
    wmsLayer: "WMS layer",
    wmsLayerIsMissing: "WMS layer is missing",

    year: "Year: ",
    yesNo: "(Yes/No)",

    zoomSelected: "Zoom selected"
};

var langCz = {
    selectAttributesToAdd: "Vyberte atributy k pridani",
    add: "Pridat",
    back: "Zpet"
};

var polyglot = new Polyglot();

if(!Config.language || Config.language == "en") {
    polyglot.extend(langEn);
} else if(Config.language == "cz") {
    polyglot.extend(langCz);
}

window.polyglot = polyglot;