var langEn = {

    abstract: "Abstract",
    activateDeactivate: "Activate/deactivate",
    activateDrawing: "Activate drawing",
    add: "Add",
    addCategory: "Add category",
    addCategorySet: "Add category set",
    addChart: "Add chart",
    adding: "Adding...",
    addingWmsLayerFailed: "Adding WMS layer failed.\n<br>",
    addLayer: "Add layer",
    administration: "Administration",
    advanced: "Advanced",
    aggregate: "Aggregate",
    all: "All",
    allAttributes: "All attributes",
    allAttributesHaveToBeNormalized: 'All attributes have to be normalized to "First selected"',
    allOptions: "All options",
    allPlaces: "All places",
    analysis: "Analysis",
    analyticalUnits: "Analytical units",
    analyticalUnitsLayers: "Analytical Units Layers",
    anonymous: "Anonymous ",
    apply: "Apply",
    area: "Area",
    areaOutlines: "Area outlines",
    areas: "Areas",
    areasAmount: "Areas {0} - {1} of {2}",
	areasFilter: "Areas filter",
    areaUnits: "Area units",
    attribute: "Attribute",
    attributesAreMissingNoLinked: "Attributes are missing! Possible reason: There are no linked attribute sets to analytical units for this place.",
    attributesAreMissingPermissions: "Attributes are missing! Possible reason: Current user does not have appropriate permissions for current configuration.",
    attributesAreMissingBrokenLinks: "Attributes are missing! Possible reason: Broken links in visualizations (e.g. non-existing attributes or attribute sets). Try to create visualizations again.",
    attributesAreMissingChoropleths: "Attributes are missing! Possible reason: Choropleths includes non-existing attributes or attribute sets. Try to create choropleths again.",
    attributeSet: "Attribute set",
    attributeUnitDisplayed: "Attribute unit - displayed",
    attributeUnitOriginal: "Attribute unit - original",
    availableLayers: "Available layers",
    average: "Average",

    back: "Back",
    backgroundLayers: "Background layers",
    badCredentials: "Bad credentials",
    bingAerial: "Bing Aerial",
    blueMarble: "Blue Marble",
    bulkEditConfiguration: "You can bulk edit configuration only for attributes with the same source units, same normalization type, change units, custom factor and for attribute and attribute set normalization also the same attribute and/or attribute set.",

    cancel: "Cancel",
    cartoDbBasemap: "Carto DB basemap",
    cat: "Cat.",
    category: "Category",
    categoryBounded: "(Category)",
    categorize: "Categorize",
    changeSettings: "Change Settings",
    choroplethParams: "Choropleth params",
    classification: "Classification",
    classType: "Class. type",
    clearSelection: "Clear selection",
    clickToActivateDeactivateFeatureInfo: "1. Click to activate/deactivate feature info &#13;2. Click on feature in map to get info",
    clickToDefineLine: "Click to define line shape, double-click to complete.",
    clickToDefinePolygon: "Click to define polygon shape, double-click to complete.",
    closeLegend: "Close legend",
    collapseAll: "Collapse all",
    collapseLastLevel: "Collapse last level",
    column: "Column",
    community: "Community",
    compare: "Compare",
    comparePeriods: "Compare periods",
    completeMetadata: "Complete Metadata",
    connectToWms: "Connect to WMS…",
    config: "Config",
    configureFilters: "Configure filters",
    configureThematicMaps: "Configure thematic maps",
    confirm: "Confirm",
    contact: "Contact",
    contextHelp: "Context help",
    continue: "Continue",
    continuous: "Continuous",
    createBlank: "Create blank",
    createCopy: "Create copy",
    create: "created",
    customFactor: "Custom factor",
    customFactorTooltip: "<p>The factor by which the default units of the attribute should be multiplied to get the units which will be displayed in this chart.</p>",
    customViews: "Custom views",
    customWms: "Custom WMS",
    customWmsLayers: "Custom WMS Layers",

    dataExploration: "Data exploration",
    dataset: "Dataset: ",
    datasetIsNotDefined: "Dataset is not defined!",
    dataViewUrl: "Data view URL",
    delete: "Delete",
    deleted: " deleted",
    deleteWholeSet: " Delete whole set ",
    detach: "Detach",
    displayedUnits: "Displayed units",
    displaying: "Displaying {0} - {1} of {2}",
    double: "Double",
    down: "Down",
    downloads: "Downloads",
    doYouReallyWantToDeleteLine: "Do you really want to delete line ",
    drawCustomAnalyticalUnits: "Draw custom Analytical units",
    drawCustomAnalyticalUnitsIsDisabled: "Drawing of custom analytical units is disabled for All places option. To enable drawing, please select place (pilot).",
    drawGreenConnectivityLine: "Draw Green Connectivity Line",
    drawingOfCustomLinesIsDisabled: "Drawing of custom lines is disabled for All places option. To enable drawing, please select place(pilot).",
    duplicateAttributesNotAllowed: "Duplicate attributes not allowed",

    error: "Error",
    equal: "Equal",
    expandLastLevel: "Expand last level",
    explore: "Explore",
    exportCsv: "Export CSV",
    exportLayerToGeoJson: "Export layer to GeoJSON",
    exportLayerToShp: "Export layer to SHP",
    exportPng: "Export PNG",
    exportToCsv: "Export to CSV",
    exportToGeoJson: "Export to GeoJSON",
    exportToShp: "Export to SHP",
    exportToXls: "Export to XLS",
    exportZip: "Export ZIP",
    extentOutline: "Extent outline",

    failedToSendRequest: "Failed to send request!",
    featureInfo: "Feature info",
    featureNameGid: "Feature name (GID)",
    file: "File",
    fillTheName: "Fill the name!",
    filter: "Filter ",
    filtersConfiguration: "Filters configuration",
    firstPage: "First Page",
    focus: "Focus: ",
    forMoreDetailsSee: "For more details see ",
    functionalUrbanArea: "Functional Urban Areas",

    group: "Group",

    help: "Help",
    hide: "Hide",
    hover: "Hover",

    importFailed: "Import failed",
    importing: "Importing…",
    incorrectLogin: "Incorrect username or password. Please try again.",
    info: "Info",
    infoLayers: "Info Layers",
    interpolate: "Interpolate",
    introduction: "Introduction",
    itWasntPossibleToLoadGroupsUsers: "It wasnt possible to load available users and groups. Please try later. Error: ",

    justSelect: "Just Select",

    keywords: "Keywords",

    lastPage: "Last Page",
    layer: "Layer",
    layerFeatureMissed: "You didn't hit any feature of the layer.",
    layerImportedSuccessfully: "Layer imported succesfully.",
	layerInfo: "Layers info",
	layerInfoDetails: "This functionality is available for Info or WMS layers only. To display information about the layer select any Info or WMS layer in Layers widget.",
    layerName: "Layer name",
    layerNameIsMissing: "Layer name is missing",
    layers: "Layers",
    layersAvailable: "Layers available",
    layersSelected: "Layers selected",
    layerSuccessfullyAdded: "Layer successfully added to Custom WMS section.",
    legend: "Legend",
    length: "Length",
    line: "line",
    liveData: "Live data",
    load: "Load",
    loadFromFile: "Load from file…",
    loadWithoutStatistics: "Load Without Statistics",
    loggedInAs: "Logged in as ",
    login: "Login",
    logIn: "Log in",
    logout: "Logout",
    logOut: "Log out",

    manageVisualizations: "Manage visualizations",
    maximise: "Maximise",
    map3d: "3D map",
    mapTools: "Map tools",
    measureLine: "Measure line",
    measurePolygon: "Measure polygon",
    metadata: "Metadata",
    minimise: "Minimise",
    modifyDisplayedUnits: "Modify Displayed Units",
    modifyDisplayedUnitsText: "<p>Modify units to be displayed in chart only in case you want to display the attribute in units other than those which are set as default for the attribute. e.g. default units are m2 and you want to display the values in km2. <br>Then the values will be multiplied by the Custom Factor (0,000001 in this case).</p>",
    multipleMaps: "Multiple maps",
    multiOptions: "Multioptions:",

    name: "Name",
    nextPage: "Next Page",
    noAreas: "No areas",
    noAreaSelected: "No area selected",
    noAttributesInfo: "No attributes or no data for selected attributes.",
    noDataToDisplay: "No data to display",
    none: "None",
    normal: "Normal",
    normalization: "Normalization",
    normalizationAttribute: "Normalization Attribute",
    normalizationAttributeAreaUnits: "Normalization attribute area units",
    normalizationAttrSet: "Normalization Attr set",
    normalizationBase: "Normalization base",
    normalizationType: "Normalization type",
    noSuchDataview: "No such dataview",
    notLoggedIn: "Not logged in",
	notQueryableLayerInfo: "Layer is not queryable.",
    numCategories: "Num categories",

    of: "of {0}",
    ok: "OK",
    onlySelected: "Only selected",
    opacity: "Opacity",
    open: "Open",
    openLegend: "Open legend",
    openStreetMap: "OpenStreetMap",
    openStreetMaps: "Open Street Maps",
    osm: "OSM",
    osmDataInformation: "<h1>OSM Data information</h1><p>Select the area for which you want to load the 3D buildings. Area is selected by double clicking on the top left corner and bottom right corner.</p>",
    other: "Other",

    page: "Page",
    password: "Password",
    percent: "Percent",
    period: "Period",
    periods: "Periods",
    pie: "Pie",
    place: "Place",
    polygon: "polygon",
    pleaseSelectAreas: "Please select areas...",
    previousPage: "Previous Page",
    producer: "Producer",
    pumaWebtoolHelp: "PUMA WebTool help",

    quantiles: "Quantiles",

    range: "(Range)",
    record: "Record ",
    refresh: "Refresh",
    resetZoom: "Reset zoom",
    resetZoomTitle: "Reset zoom level 1:1",
    remove: "Remove",
    reload: "Reload",
    requestHasBeenSent: "Request has been sent...",
    reports: "Reports",
    reset: "Reset",

    save: "Save",
    saved: "Saved!",
    saveAs: "Save as",
    saveAsImage: "Save as image",
    saveDataView: "Save data view",
    savedConfigurations: "Saved configurations",
    saveSetName: "Save set name",
    saveView: "Save view",
    saveVisualization: "Save visualization",
    scatter: "Scatter",
    scope: "Scope",
    searchForMetadataStarted: "Search for metadata has started. Please wait.",
    select: "Select",
    selectAttributesToAdd: "Select attributes to add",
    selectCity: "",
    selectedAreas: "Selected areas",
    selectedAreasFilled: "Selected areas filled",
    selectedLayers: "Selected layers",
    selectEnd: "Select end",
    selectInMap: "Select in map",
    selectionGuide: "<h2>Selection guide</h2><h3>Scope</h3><p>Different data address different scope level of analysis. Please choose your scope of interest.</p><h3>Place</h3><p>Data for different analysis scopes can be available for different places. Please select place covered / prepared for exploration and analysis according to region, country or city of your interest.</p><h3>Theme</h3><p>Standard views on data are focused on different thematic information. Please select theme according your thematic interests.</p>",
    selections: "Selections",
    selectPeriod: "Select period",
    selectPeriodsToCompare: "Select periods to compare",
    selectPlace: "Select place...",
    selectScope: "Select scope...",
    selectStart: "Select start",
    selectTheme: "Select theme...",
    send: "Send",
    set: "Set",
    setting: "Setting",
    settings: "Settings",
    share: "Share",
    shareDataView: "Share data view",
    shareOnPortal: "Share on portal",
    shareView: "Share view",
	sharingDescriptionLabel: "Description",
	sharingGroupLabel: "Select group",
	sharingLangLabel: "Language",
	sharingMetadataDescription: "Enter dataview name and short description of the current state, which will be shared.",
	sharingMetadataTitle: "Set dataview metadata",
	sharingNameLabel: "Name",
	sharingPermissionsDescription: "... ",
	sharingPermissionsTitle: "Update permissions",
	sharingUserLabel: "Select user",
	show: "Show",
    showCustomAnalyticalUnitsLayer: "Show Custom Analytical units Layer",
    showInChart: "Show in chart",
    signUp: "Sign up",
    snapshot: "Snapshot",
    snapshotCreationStarted: "Snapshot creation started",
    snapshotDone: "Snapshot done",
    snapshots: "Snapshots",
    stacking: "Stacking",
    started: "started",
    startCreating: "start creating",
    startUpdating: "start updating",
    switchZooming: "Switch zooming",

    table: "Table",
    takeMapSnapshot: "Take map snapshot",
    temporalExtent: "Temporal extent",
    theme: "Theme: ",
    thematicLayers: "Thematic Layers",
    thematicMaps: "Thematic maps",
    thematicMapsConfiguration: "Thematic maps configuration",
    theStateWasCorrectlyShared: "The state was correctly shared. The user has access to current state via URL: ",
    thereWasAnIssueWithSharing: "There was an issue with storing current state of the application. Error: ",
    timedOut: "Timed out, process can still be running on server",
    title: "Title",
    tools: "Tools",
    treeAll: "Tree all",
    treeLowestLevel: "Tree lowest level",
    type: "Type",

    undefined: "Undefined",
    undefinedError: "Undefined error",
    units: "Units",
    unselectActiveSelection: "Unselect active selection",
    unselectAll: "Unselect all",
    up: "Up",
    updated: "updated",
    urbanDynamicTool: "UrbanDynamic tool",
    URL: "URL",
    user: "User",

    value: "Value",
    visu: "Visualization",
    visualization: "Visualization: ",
    visualizations: "Visualizations",

    warning: "Warning",
    wasReset: " was reset",
    wmsAddress: "WMS address",
    wmsAddressIsMissing: "WMS address is missing or incorrect",
    wmsLayer: "WMS layer",
    wmsLayerIsMissing: "WMS layer is missing",

    year: "Year: ",
    yesNo: "(Yes/No)",

    zoomSelected: "Zoom selected"
};

var langCz = {

    abstract: "Abstrakt",
    activateDeactivate: "Aktivovat/deaktivovat",
    activateDrawing: "Aktivovat kreslení",
    add: "Přidat",
    addCategory: "Přidat kategorii",
    addCategorySet: "Přidat sadu kategorií",
    addChart: "Přidat graf",
    adding: "Nahrávám...",
    addingWmsLayerFailed: "Přidání WMS vrstvy neuspělo.\n<br>",
    addLayer: "Přidat vrstvu",
    administration: "Administrace",
    advanced: "Pokročilé",
    aggregate: "Aggregovat",
    all: "Vše",
    allAttributes: "Všechny atributy",
    allAttributesHaveToBeNormalized: 'Všechny atributy musí být normalizované ve stylu "První vybraný"',
    allOptions: "Všechny možnosti",
    allPlaces: "Všechna místa",
    analysis: "Analýza",
    analyticalUnits: "Analztické jednotky",
    analyticalUnitsLayers: "Vrstvy analytických jednotek",
    anonymous: "Anonymní ",
    apply: "Použít",
    area: "Území",
    areaOutlines: "Obrys území",
    areas: "Území",
    areasAmount: "Území {0} - {1} z {2}",
    areasFilter: "Filtrování území",
    areaUnits: "Plošné jednotky",
    attribute: "Atribut",
    attributesAreMissingNoLinked: "Chybí atributy! Možný důvod: K tomuto místu nejsou připojené žádné skupiny atributů.",
    attributesAreMissingPermissions: "Chybí atributy! Možný důvod: Aktuální uživatel nemá dostatečná práva k této konfiguraci.",
    attributesAreMissingBrokenLinks: "Chybí atributy! Možný důvod: Rozbité vazby ve vizualizaci (např. neexistující atributz nebo skupinz atributů). Zkuste znovu vytvořit vizualizaci.",
    attributesAreMissingChoropleths: "Chybí atributy! Možný důvod: Kartogramy obsahují neexistující atributy nebo skupiny atributů. Zkuste znovu vytvořit kartogram.",
    attributeSet: "Skupina atributů",
    attributeUnitDisplayed: "Jednotka atributu - zobrazovaná",
    attributeUnitOriginal: "Jednotka atributu - původní",
    availableLayers: "Dostupné vrstvy",
    average: "Průměr",

    back: "Zpět",
    backgroundLayers: "Podkladové vrstvy",
    badCredentials: "Chybné přihlašovací údaje",
    bingAerial: "Bing letecký pohled",
    blueMarble: "Blue Marble",
    bulkEditConfiguration: "Hromadně je možné upravovat konfiguraci pouze pro atributy se stejnými původními jednotkami, stejnou normalizací, stejným typem úpravy jednotek, stejným faktorem pro úpravu a v případě normalizace přes skupinu atributů také stejný atribut/ skupina atributů.",

    cancel: "Zrušit",
    cartoDbBasemap: "Carto DB základní mapa",
    cat: "Kat.",
    category: "Kategorie",
    categoryBounded: "(Kategorie)",
    categorize: "Kategorizovat",
    changeSettings: "Změna nastavení",
    choroplethParams: "Parametry kartogramu",
    classification: "Klasifikace",
    classType: "Typ klasifikace",
    clearSelection: "Zrušit výběr",
    clickToActivateDeactivateFeatureInfo: "1. Klikněte pro zapnutí/vypnutí informací o jednotce &#13;2. Klikněte na jednotku v mapě pro získání informací o ní.",
    clickToDefineLine: "Klikněte pro vytvoření nové čáry, klikněte dvakrát pro dokončení.",
    clickToDefinePolygon: "Klikněte pro vytvoření nového polygonu, klikněte dvakrát pro dokončení.",
    closeLegend: "Zavřít legendu",
    collapseAll: "Sbalit vše",
    collapseLastLevel: "Sbalit poslední úroveň",
    column: "Sloupec",
    community: "Komunita",
    compare: "Porovnat",
    comparePeriods: "Porovnat periody",
    completeMetadata: "Kompletní metadata",
    connectToWms: "Připojit WMS ...",
    config: "Konfigurace",
    configureFilters: "Nastavení filtrů",
    configureThematicMaps: "Nastavení kartogramů",
    confirm: "Potvrdit",
    contact: "Kontakt",
    contextHelp: "Kontextový help",
    continue: "Pokračovat",
    continuous: "Spojitý",
    createBlank: "Vytvořit prázdný",
    createCopy: "Vytvořit kopii",
    create: "vytvořený",
    customFactor: "Specifický faktor",
    customFactorTooltip: "<p>Faktor specifikující jak budou upraveny defaultní jednotky atributu pro to, abyste získali jednotky zobrazené v grafu.</p>",
    customViews: "Další náhledy",
    customWms: "Další WMS",
    customWmsLayers: "Další WMS vrstvy",

    dataExploration: "Průzkum dat",
    dataset: "Datová sada: ",
    datasetIsNotDefined: "Datová sada není definovaná!",
    dataViewUrl: "URL pro náhled na data",
    delete: "Smazat",
    deleted: " smazáno",
    deleteWholeSet: " Smazat celou skupinu ",
    detach: "Uvolnit",
    displayedUnits: "Zobrazené jednotky",
	displaying: "Zobrazeno {0} - {1} z {2}",
	double: "Dvojnásobek",
    down: "Dolu",
    downloads: "Ke stažení",
    doYouReallyWantToDeleteLine: "Opravdu chcete smazat čáru ",
    drawCustomAnalyticalUnits: "Nakreslit novou analztickou jednotku",
    drawCustomAnalyticalUnitsIsDisabled: "Kreslení nové analytické jednotky je zakázané pro možnost všechna místa. Pro povolení prosím vyberte konkrétní místo (pilot).",
    drawGreenConnectivityLine: "Nakreslete čáru představující propojení zeleně",
    drawingOfCustomLinesIsDisabled: "Nakreslení nové čáry je zakázané pro možnost všechna místa. Pro povolení prosím vyberte konkrétní místo (pilot).",
    duplicateAttributesNotAllowed: "Duplikování atributů není povoleno.",

    error: "Chyba",
    equal: "Stejný",
    expandLastLevel: "Rozbalte poslední úroveň",
    explore: "Prozkoumat",
    exportCsv: "Export CSV",
    exportLayerToGeoJson: "Export vrstvy do GeoJSON",
    exportLayerToShp: "Export vrstvy do SHP",
    exportPng: "Export PNG",
    exportToCsv: "Export do CSV",
    exportToGeoJson: "Export do GeoJSON",
    exportToShp: "Export do SHP",
    exportToXls: "Export do XLS",
    exportZip: "Export ZIP",
    extentOutline: "Znázornění ohraničené oblasti",

    failedToSendRequest: "Nepovedlo se poslat požadavek!",
    featureInfo: "Informace o jednotce",
    featureNameGid: "Jméno jednotky (GID)",
    file: "Soubor",
    fillTheName: "Zadejte jméno!",
    filter: "Filtr ",
    filtersConfiguration: "Nastavení filtrů",
	firstPage: "První Stránka",
	focus: "Ohnisko: ",
    forMoreDetailsSee: "Pro více detailů ",
    functionalUrbanArea: "Funkční městské oblasti",

    group: "Skupina",

    help: "Help",
    hide: "Skrýt",
    hover: "Hover",

    importFailed: "Import neuspěl",
    importing: "Importuji…",
    incorrectLogin: "Chybné uživatelské jméno nebo heslo. Zkuste to prosím znovu.",
    info: "Info",
    infoLayers: "Informační vrstvy",
    interpolate: "Interpolovat",
    introduction: "Úvod",
    itWasntPossibleToLoadGroupsUsers: "Nebylo možné načíst dostupné uživatele a skupiny. Zkuste to prosím později. Chyba: ",

    justSelect: "Pouze vybrat",

    keywords: "Klíčová slova",

	lastPage: "Poslední stránka",
	layer: "Vrstva",
	layerFeatureMissed: "Žádný prvek pro danou pozici.",
    layerImportedSuccessfully: "Vrstva byla úspěšně naimportována",
	layerInfo: "Informace o vrstvách",
    layerInfoDetails: "Tato funkce je dostupná pouze pro Informační a WMS vrstvy. Pro zobrazení informacích o vrstvě vyberte prosím jakoukoli Informační nebo WMS vrstvu z panelu Vrstvy.",
    layerName: "Jméno vrstvy",
    layerNameIsMissing: "Jméno vrstvy chybí",
    layers: "Vrstvy",
    layersAvailable: "Dostupné vrstvy",
    layersSelected: "Vybrané vrstvy",
    layerSuccessfullyAdded: "Vrstav úspěšně přidána do sekce Další WMS vrstvy.",
    legend: "Legenda",
    length: "Délka",
    line: "čára",
    liveData: "Živá data",
    load: "Načíst",
    loadFromFile: "Načíst ze souboru...",
    loadWithoutStatistics: "Načíst bez statistik",
    loggedInAs: "Přihlášen jako ",
    login: "Přihlásit",
    logIn: "Přihlásit",
    logout: "Odhlásit",
    logOut: "Odhlásit",

    manageVisualizations: "Spravovat vizualizace",
    maximise: "Maximalizovat",
    map3d: "3D mapa",
    mapTools: "Mapové nástroje",
    measureLine: "Měření délky",
    measurePolygon: "Měření území",
    metadata: "Metadata",
    minimise: "Skrýt",
    modifyDisplayedUnits: "Upravit zobrazené jednotky",
    modifyDisplayedUnitsText: "<p>Jednotky pro zobrazení v grafu upravte pouze v případě že chcete zobrazit atribut v jiných jednotkách než ty které jsou defaultně nastavené. Například defaultní jednotky jsou m2 a vy chcete zobrazit hodnoty v km2. <br>V takovém případě budou jednotky vynásobené Faktorem (0,000001 v tomto případě).</p>",
    multipleMaps: "Vícero map",
    multiOptions: "Více možností:",

    name: "Jméno",
	nextPage: "Další stránka",
	noAreas: "Žádná jednotka",
    noAreaSelected: "Žádná jednotka není vybraná",
	noAttributesInfo: "K této jednotce se neváží žádné atributy.",
	noDataToDisplay: "Žádná data k zobrazení",
	none: "Žádný",
    normal: "Normální",
    normalization: "Normalizace",
    normalizationAttribute: "Atribut použitý pro normalizaci",
    normalizationAttributeAreaUnits: "Jednotky atributu určeného k normalizaci",
    normalizationAttrSet: "Skupina atributů pro normalizaci",
    normalizationBase: "Základ pro normalizaci",
    normalizationType: "Typ normalizace",
    noSuchDataview: "Není žádný takový uložený náhled",
    notLoggedIn: "Nepřihlášen",
	notQueryableLayerInfo: "Na prvky ve vrstvě se nelze dotazovat.",
    numCategories: "Počet kategorií",

	of: "z {0}",
	ok: "OK",
    onlySelected: "Pouze vybrané",
    opacity: "Průhlednost",
    open: "Otevřít",
    openLegend: "Otevřít legendu",
    openStreetMap: "OpenStreetMap",
    openStreetMaps: "Open Street Maps",
    osm: "OSM",
    osmDataInformation: "<h1>OSM Datové informace</h1><p>Vyberte území pro které chcete načíst 3D budovy. Území vyberete dvojitým kliknutím na levý horní roh následovaným dvojitým kliknutím na pravý spodní roh.</p>",
    other: "Ostatní",

	page: "Strana",
	password: "Heslo",
    percent: "Procenta",
    period: "Časové období",
    periods: "Časová období",
    pie: "Koláčový graf",
    place: "Místo",
    polygon: "polygon",
    pleaseSelectAreas: "Prosím vyberte území...",
	previousPage: "Předchozí stránka",
	producer: "Tvůrce",
    pumaWebtoolHelp: "PUMA WebTool help",

    quantiles: "Quantily",

    range: "(Rozsah)",
    record: "Záznam ",
	refresh: "Obnovit",
	resetZoom: "Zrušit přiblížení",
	resetZoomTitle: "Zrušit přiblížení na úroveň 1:1",
	remove: "Odstranit",
    reload: "Načíst",
    reports: "Grafy",
    requestHasBeenSent: "Požadavek byl zaslán...",
    reset: "Reset",

    save: "Uložit",
    saved: "Uloženo!",
    saveAs: "Uložit jako",
    saveAsImage: "Uložit jako obrázek",
    saveDataView: "Uložit náhled",
    savedConfigurations: "Uložené nastavení",
    saveSetName: "Uložit jméno skupiny",
    saveView: "Uložit náhled",
    saveVisualization: "Uložit vizualizaci",
    scatter: "Scatter",
    scope: "Kategorie",
    searchForMetadataStarted: "Prosím počkejte než se načtou metadata.",
    select: "Výběr",
    selectAttributesToAdd: "Vyberte atributy k přidání",
    selectCity: "Vyberte město",
    selectedAreas: "Vybraná území",
    selectedAreasFilled: "Vyplněná vybraná území",
    selectedLayers: "Vybrané vrstvy",
    selectEnd: "Výběr konce",
    selectInMap: "Výběr v mapě",
    selectionGuide: "<h2>Přiručka pro výběr</h2><h3>Kategorie</h3><p>Různá data spadají pod různé kategorie.</p><h3>Místo</h3><p>Každá kategorie obsahuje svou vlastní sadu míst. Vyberte si to, které vás zajímá.</p><h3>Téma</h3><p>Data jsou dále tříděna do kategorií podle zájmových oblastí. Vyberte si tedy také zájmovou oblast.</p>",
    selections: "Výběry",
    selectPeriod: "Vyberte časové období",
    selectPeriodsToCompare: "Vyberte časová období pro porovnání",
    selectPlace: "Vyberte místo...",
    selectScope: "Vyberte scope...",
    selectStart: "Výběr začátku",
    selectTheme: "Vyberte téma...",
    send: "Poslat",
    set: "Nastavit",
    setting: "Nastavení",
    settings: "Nastavení",
    share: "Sdílení",
    shareDataView: "Sdílet náhled",
    shareView: "Sdílet",
    shareOnPortal: "Sdílet v portálu",
	sharingDescriptionLabel: "Stručný popis",
	sharingGroupLabel: "Vyber skupinu",
	sharingLangLabel: "Jazyk",
	sharingMetadataDescription: "Zadejte název a krátký popis aktuálního stavu, který budete sdílet.",
	sharingMetadataTitle: "Nastavení metadat náhledu",
	sharingNameLabel: "Název",
	sharingPermissionsDescription: "...",
	sharingPermissionsTitle: "Úprava přístupových práv",
	sharingUserLabel: "Vyber uživatele",
	show: "Zobraz",
    showCustomAnalyticalUnitsLayer: "Zobrazit vrstvu dalších analytických jednotek",
    showInChart: "Zobrazit v grafu",
    signUp: "Registrace",
    snapshot: "Náhled",
    snapshotCreationStarted: "Začala tvorba náhledu",
    snapshotDone: "Náhled vytvořen",
    snapshots: "Náhledy",
    stacking: "Stacking",
    started: "začalo",
    startCreating: "začátek vytváření",
    startUpdating: "začátek upravování",
    switchZooming: "Změnit zoom",

    table: "Tabulka",
    takeMapSnapshot: "Vytvořit náhled na mapu",
    temporalExtent: "Časový rozsah",
    theme: "Téma: ",
    thematicLayers: "Kartogramy",
    thematicMaps: "Kartogramy",
    thematicMapsConfiguration: "Nastavování kartogramů",
    theStateWasCorrectlyShared: "Aktuální stav aplikace byl korektně uložen. Uživatelk němu má přístup přes URL: ",
    thereWasAnIssueWithSharing: "Aktuální stav aplikace se nepovedlo korektně uložit. Chyba: ",
    timedOut: "Chyba spojení, proces může stále běžet na serveru",
    title: "Titulek",
    tools: "Nástroje",
    treeAll: "Strom vše",
    treeLowestLevel: "Strom nejdetailnější úroveň",
    type: "Typ",

    undefined: "Nedfinováno",
    undefinedError: "Nedefinovaná chyba",
    units: "Jednotky",
    unselectActiveSelection: "Odstranit aktuální výběr",
    unselectAll: "Odstranit všechny aktivní výběry",
    up: "Nahoru",
    updated: "upraveno",
    urbanDynamicTool: "UrbanDynamic nástroj",
    URL: "URL",
    user: "Uživatel",

    value: "Hodnota",
    visu: "Vizualizace",
    visualization: "Vizualizace: ",
    visualizations: "Vizualizace",

    warning: "Varování",
    wasReset: " byl vyčistěn",
    wmsAddress: "WMS adresa",
    wmsAddressIsMissing: "WMS adresa chybí nebo je chybná",
    wmsLayer: "WMS vrstva",
    wmsLayerIsMissing: "WMS vrstva chybí",

    year: "Rok: ",
    yesNo: "(Ano/Ne)",

    zoomSelected: "Zoom na vybrané"
};

var polyglot = new Polyglot();

var urlLang = new URL(window.location).searchParams.get('lang');
if ((!Config.language && !urlLang) || Config.language == "en" || urlLang == "en") {
    polyglot.extend(langEn);
} else if (Config.language == "cz" || urlLang == 'cz') {
    polyglot.extend(langCz);
}

window.polyglot = polyglot;